apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
  namespace: kubernetes-dashboard
data:
  # ============ DOCKER & NETWORK ============
  DOCKER_HOST_IP: "localhost"

  # ============ DATABASE CONFIGURATION ============
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "library_management"
  DB_USERNAME: "postgres"
  DATASOURCE_HOST: "postgres-service"

  # ============ KEYCLOAK CONFIGURATION ============
  KEYCLOAK_HOST: "keycloak"
  KEYCLOAK_ADMIN_USERNAME: "admin"

  # ============ CONFIG SERVER ============
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8889"

  # ============ EUREKA SERVER ============
  EUREKA_SERVER_HOST: "eureka-server"
  EUREKA_SERVER_PORT: "8761"
  EUREKA_HOST: "eureka-server"

  # ============ API GATEWAY ============
  API_GATEWAY_HOST: "api-gateway"
  API_GATEWAY_PORT: "8888"

  # ============ KAFKA CONFIGURATION ============
  KAFKA_EXTERNAL_PORT: "9092"
  KAFKA_DOCKER_PORT: "29092"
  KAFKA_BROKER_ID: "1"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  ZOOKEEPER_PORT: "2181"
  KAFKA_SERVER: "kafka-service"

  # ============ MICROSERVICES CONFIGURATION ============
  # Member Service
  MEMBER_SERVICE_HOST: "member-service"
  MEMBER_SERVICE_PORT: "9993"
  # Catalog Service
  CATALOG_SERVICE_HOST: "catalog-service"
  CATALOG_SERVICE_PORT: "9991"
  # Loan Service
  LOAN_SERVICE_HOST: "loan-service"
  LOAN_SERVICE_PORT: "9995"
  # Notification Service
  NOTIFICATION_SERVICE_HOST: "notification-service"
  NOTIFICATION_SERVICE_PORT: "9994"
  # Dashboard Service
  DASHBOARD_SERVICE_HOST: "dashboard-service"
  DASHBOARD_SERVICE_PORT: "9992"

  # Service URLs
  CONFIG_SERVER_URL: "http://config-server-service:8889"
  API_GATEWAY_URL: "http://api-gateway-service:8888"

---
apiVersion: v1
kind: Secret
metadata:
  name: library-secrets
  namespace: kubernetes-dashboard
type: Opaque
data:
  # Base64 encoded values - you should replace these with actual encoded secrets
  # echo -n 'your_password' | base64
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=      # admin
  KEYCLOAK_CLIENT_SECRET: a2lhOHdMQ2JmbEN1cDZxOFRMNWpnTFVkY1lEaXZxQmI=  # kia8wLCbflCup6q8TL5jgLUdcYDivqBb