spring:
  application:
    name: ${SPRING_APPLICATION_NAME:library-service}

# Logging Configuration
logging:
  config: classpath:logback-spring.xml
  level:
    com.library: DEBUG
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: INFO
  pattern:
    # Console pattern for development
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%X{requestId}]){magenta} %clr([%X{correlationId}]){blue} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

# Application specific logging configuration
app:
  logging:
    # Enable/disable detailed logging globally
    detailed-enabled: ${DETAILED_LOGGING_ENABLED:false}
    # Default sampling rate for detailed logging (0.0 to 1.0)
    default-sampling-rate: ${DEFAULT_SAMPLING_RATE:0.1}
    # Performance thresholds
    slow-request-threshold-ms: ${SLOW_REQUEST_THRESHOLD:1000}
    very-slow-request-threshold-ms: ${VERY_SLOW_REQUEST_THRESHOLD:5000}
    # Enable performance monitoring
    performance-monitoring-enabled: ${PERFORMANCE_MONITORING_ENABLED:true}
    # Enable sensitive data sanitization
    sanitize-sensitive-data: ${SANITIZE_SENSITIVE_DATA:true}
    # Log file retention
    log-retention-days: ${LOG_RETENTION_DAYS:30}
    # Maximum log file size
    max-log-file-size: ${MAX_LOG_FILE_SIZE:100MB}

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    loggers:
      enabled: true
  metrics:
    enable:
      jvm: true
      system: true
      http: true
