server:
  port: 8081

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/book-service
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
logging:
  level:
    org.springframework.security: DEBUG
