server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/user-service
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:library-realm}
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:library-realm}/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    security:
      protocol: plaintext
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 30
      compression-type: lz4
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true

app:
  jwt:
    secret: d6d9vYwRjZ0C5P1w72wYJ+PGgKYTWm6u83rXJwVQSO8jxTDV+jMp1+XO9Mg4Xz0+nYOvivTOLXi/L4vXxzvC1A==
    expiration:
      access: 9000000      # 15 minutes
      refresh: 2592000000 # 30 days
  library-card:
    default-validity-years: ${LIBRARY_CARD_DEFAULT_VALIDITY_YEARS:1}
    expiring-soon-days: ${LIBRARY_CARD_EXPIRING_SOON_DAYS:30}

keycloak:
  server-url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:library-realm}
  admin:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

logging:
  level:
    com.library.user: DEBUG
    org.springframework.security: DEBUG